import type {
  CurrentUser,
  Customer,
  DashboardStatsData,
  Employee,
  Job,
} from '../types/app'

/**
 * ============================================================================
 * MOCK DATA SOURCE
 * ============================================================================
 * NOTE: These mock entities are temporary frontend fixtures for UI rendering.
 * In future API integration phases, these will be replaced with real backend
 * responses from auth and data endpoints.
 */

export const mockCurrentUser: CurrentUser = {
  id: 'usr_001',
  name: 'Sofia Bennett',
  email: 'sofia.bennett@fieldops.io',
  role: 'OWNER',
  organizationName: 'Apex Field Services',
}

export const mockDashboardStats: DashboardStatsData = {
  totalEmployees: {
    label: 'Total Employees',
    value: 24,
    change: '+3 this month',
    isPositive: true,
    description: '18 active in field',
  },
  totalCustomers: {
    label: 'Total Customers',
    value: 142,
    change: '+12% vs last month',
    isPositive: true,
    description: '98 active service contracts',
  },
  activeJobs: {
    label: 'Active Jobs',
    value: 38,
    change: '8 in progress now',
    isPositive: true,
    description: '30 scheduled for today',
  },
  pendingJobs: {
    label: 'Pending Approval',
    value: 7,
    change: 'Requires dispatch',
    isPositive: false,
    description: 'Avg dispatch time: 18m',
  },
}

export const mockEmployees: Employee[] = [
  {
    id: 'emp_001',
    firstName: 'Sofia',
    lastName: 'Bennett',
    name: 'Sofia Bennett',
    email: 'sofia.bennett@apexops.io',
    phone: '+1 (555) 234-5678',
    role: 'OWNER',
    department: 'Executive Management',
    status: 'ACTIVE',
    assignedJobsCount: 2,
    joinedDate: '2023-01-15',
    avatarColor: 'bg-blue-600',
  },
  {
    id: 'emp_002',
    firstName: 'Marcus',
    lastName: 'Vance',
    name: 'Marcus Vance',
    email: 'marcus.vance@apexops.io',
    phone: '+1 (555) 345-6789',
    role: 'ADMIN',
    department: 'Operations',
    status: 'ACTIVE',
    assignedJobsCount: 4,
    joinedDate: '2023-03-10',
    avatarColor: 'bg-indigo-600',
  },
  {
    id: 'emp_003',
    firstName: 'Elena',
    lastName: 'Rostova',
    name: 'Elena Rostova',
    email: 'elena.rostova@apexops.io',
    phone: '+1 (555) 456-7890',
    role: 'MANAGER',
    department: 'Dispatch & Logistics',
    status: 'ACTIVE',
    assignedJobsCount: 6,
    joinedDate: '2023-05-22',
    avatarColor: 'bg-violet-600',
  },
  {
    id: 'emp_004',
    firstName: 'David',
    lastName: 'Chen',
    name: 'David Chen',
    email: 'david.chen@apexops.io',
    phone: '+1 (555) 567-8901',
    role: 'EMPLOYEE',
    department: 'HVAC & Climate Systems',
    status: 'ACTIVE',
    assignedJobsCount: 5,
    joinedDate: '2023-08-14',
    avatarColor: 'bg-emerald-600',
  },
  {
    id: 'emp_005',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@apexops.io',
    phone: '+1 (555) 678-9012',
    role: 'EMPLOYEE',
    department: 'Electrical Maintenance',
    status: 'ACTIVE',
    assignedJobsCount: 4,
    joinedDate: '2023-09-01',
    avatarColor: 'bg-teal-600',
  },
  {
    id: 'emp_006',
    firstName: 'James',
    lastName: 'Wilson',
    name: 'James Wilson',
    email: 'james.wilson@apexops.io',
    phone: '+1 (555) 789-0123',
    role: 'EMPLOYEE',
    department: 'Plumbing & Hydraulic',
    status: 'ON_LEAVE',
    assignedJobsCount: 0,
    joinedDate: '2023-10-11',
    avatarColor: 'bg-amber-600',
  },
  {
    id: 'emp_007',
    firstName: 'Rachel',
    lastName: 'Adams',
    name: 'Rachel Adams',
    email: 'rachel.adams@apexops.io',
    phone: '+1 (555) 890-1234',
    role: 'EMPLOYEE',
    department: 'Security & Telemetry',
    status: 'ACTIVE',
    assignedJobsCount: 3,
    joinedDate: '2024-01-20',
    avatarColor: 'bg-cyan-600',
  },
  {
    id: 'emp_008',
    firstName: 'Robert',
    lastName: 'Taylor',
    name: 'Robert Taylor',
    email: 'robert.taylor@apexops.io',
    phone: '+1 (555) 901-2345',
    role: 'EMPLOYEE',
    department: 'Heavy Equipment',
    status: 'INACTIVE',
    assignedJobsCount: 0,
    joinedDate: '2023-02-18',
    avatarColor: 'bg-slate-600',
  },
]

export const mockCustomers: Customer[] = [
  {
    id: 'cust_001',
    name: 'Metropolitan Hospital Center',
    contactPerson: 'Dr. Arthur Sterling',
    email: 'facilities@metropolitanhealth.org',
    phone: '+1 (555) 111-2233',
    address: '450 East 29th Street',
    city: 'New York',
    state: 'NY',
    zipCode: '10016',
    status: 'ACTIVE',
    totalJobs: 28,
    lastServiceDate: '2026-09-18',
  },
  {
    id: 'cust_002',
    name: 'Horizon Logistics Park',
    contactPerson: 'Claire Davenport',
    email: 'cdavenport@horizonlogistics.com',
    phone: '+1 (555) 222-3344',
    address: '8800 Industrial Parkway',
    city: 'Jersey City',
    state: 'NJ',
    zipCode: '07305',
    status: 'ACTIVE',
    totalJobs: 19,
    lastServiceDate: '2026-09-19',
  },
  {
    id: 'cust_003',
    name: 'Beacon Tower Residences',
    contactPerson: 'Gabriel Mendez',
    email: 'gmendez@beacontowerny.com',
    phone: '+1 (555) 333-4455',
    address: '120 Broadway Ave',
    city: 'New York',
    state: 'NY',
    zipCode: '10271',
    status: 'ACTIVE',
    totalJobs: 14,
    lastServiceDate: '2026-09-15',
  },
  {
    id: 'cust_004',
    name: 'Omni Retail Plaza',
    contactPerson: 'Samantha Brooks',
    email: 'sbrooks@omniretail.com',
    phone: '+1 (555) 444-5566',
    address: '2200 Grand Concourse',
    city: 'Bronx',
    state: 'NY',
    zipCode: '10457',
    status: 'PENDING',
    totalJobs: 3,
    lastServiceDate: '2026-09-02',
  },
  {
    id: 'cust_005',
    name: 'Summit Data Centers LLC',
    contactPerson: 'Kevin Patel',
    email: 'kpatel@summitdatacenter.net',
    phone: '+1 (555) 555-6677',
    address: '700 Technology Drive',
    city: 'Newark',
    state: 'NJ',
    zipCode: '07102',
    status: 'ACTIVE',
    totalJobs: 34,
    lastServiceDate: '2026-09-20',
  },
  {
    id: 'cust_006',
    name: 'Riverside Corporate Suites',
    contactPerson: 'Valerie King',
    email: 'vking@riversidesuites.com',
    phone: '+1 (555) 666-7788',
    address: '500 River Road',
    city: 'Edgewater',
    state: 'NJ',
    zipCode: '07020',
    status: 'INACTIVE',
    totalJobs: 8,
    lastServiceDate: '2026-07-28',
  },
  {
    id: 'cust_007',
    name: 'Vanguard Manufacturing Corp',
    contactPerson: 'Gregory Thorne',
    email: 'g.thorne@vanguardmfg.io',
    phone: '+1 (555) 777-8899',
    address: '1400 Harbor Blvd',
    city: 'Weehawken',
    state: 'NJ',
    zipCode: '07086',
    status: 'ACTIVE',
    totalJobs: 22,
    lastServiceDate: '2026-09-14',
  },
]

export const mockJobs: Job[] = [
  {
    id: 'job_101',
    jobNumber: 'JOB-8492',
    title: 'Emergency HVAC Compressor Replacement',
    customerName: 'Metropolitan Hospital Center',
    customerId: 'cust_001',
    assignedEmployeeName: 'David Chen',
    assignedEmployeeId: 'emp_004',
    status: 'IN_PROGRESS',
    priority: 'URGENT',
    scheduledDate: '2026-09-21 09:00 AM',
    location: '450 East 29th St, NY',
    estimatedDuration: '3.5 hrs',
  },
  {
    id: 'job_102',
    jobNumber: 'JOB-8493',
    title: 'Bi-Annual Generator Electrical Inspection',
    customerName: 'Summit Data Centers LLC',
    customerId: 'cust_005',
    assignedEmployeeName: 'Sarah Jenkins',
    assignedEmployeeId: 'emp_005',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    scheduledDate: '2026-09-21 11:30 AM',
    location: '700 Tech Dr, Newark, NJ',
    estimatedDuration: '4.0 hrs',
  },
  {
    id: 'job_103',
    jobNumber: 'JOB-8494',
    title: 'Loading Bay Hydraulic Ramp Maintenance',
    customerName: 'Horizon Logistics Park',
    customerId: 'cust_002',
    assignedEmployeeName: 'Rachel Adams',
    assignedEmployeeId: 'emp_007',
    status: 'SCHEDULED',
    priority: 'MEDIUM',
    scheduledDate: '2026-09-21 02:00 PM',
    location: '8800 Industrial Pkwy, NJ',
    estimatedDuration: '2.0 hrs',
  },
  {
    id: 'job_104',
    jobNumber: 'JOB-8495',
    title: 'Main Water Line Pressure Calibration',
    customerName: 'Beacon Tower Residences',
    customerId: 'cust_003',
    assignedEmployeeName: 'David Chen',
    assignedEmployeeId: 'emp_004',
    status: 'SCHEDULED',
    priority: 'LOW',
    scheduledDate: '2026-09-22 10:00 AM',
    location: '120 Broadway, NY',
    estimatedDuration: '1.5 hrs',
  },
  {
    id: 'job_105',
    jobNumber: 'JOB-8496',
    title: 'Site Telemetry Sensor Audit & Reconfiguration',
    customerName: 'Vanguard Manufacturing Corp',
    customerId: 'cust_007',
    assignedEmployeeName: 'Rachel Adams',
    assignedEmployeeId: 'emp_007',
    status: 'PENDING',
    priority: 'MEDIUM',
    scheduledDate: '2026-09-22 01:30 PM',
    location: '1400 Harbor Blvd, NJ',
    estimatedDuration: '3.0 hrs',
  },
  {
    id: 'job_106',
    jobNumber: 'JOB-8497',
    title: 'Chiller Unit Preventative Overhaul',
    customerName: 'Omni Retail Plaza',
    customerId: 'cust_004',
    assignedEmployeeName: 'Sarah Jenkins',
    assignedEmployeeId: 'emp_005',
    status: 'COMPLETED',
    priority: 'HIGH',
    scheduledDate: '2026-09-20 04:00 PM',
    location: '2200 Grand Concourse, NY',
    estimatedDuration: '5.0 hrs',
  },
]
